### ISSUE TITLE
API Research

### ISSUE THREAD

**Issue by HustinKava** [P3TeamTwo/p3#14]
Twilio
HealThruWords

**Comment by enochj316** [comment]
https://rapidapi.com/mirror-dev-team/api/mirror-ai/pricing - Avatar Creator - 300 Requests/day

**Comment by enochj316** [comment]
https://api.adviceslip.com/

**Comment by enochj316** [comment]
affirmations.dev - Random affirmations {"affirmation":"Sucking at something is the first step towards being good at something"}

**Comment by enochj316** [comment]
https://rapidapi.com/nexmo/api/nexmo-sms-messaging/pricing - send SMS to user - $10/mnth for 100000 msg
